---
# tasks file for rpi-install-noip-dynamic-update-client

- name: Download the TODO
  get_url:
    url: http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
    dest: /usr/local/src/

- name: Unpack the TODO
  unarchive:
    src: /usr/local/src/noip-duc-linux.tar.gz
    dest: /usr/local/src/
    remote_src: yes

- name: Install make
  apt:
    name: make
    state: present

- name: Install gcc
  apt:
    name: gcc
    state: present

- name: Run make
  community.general.make:
    chdir: /usr/local/src/noip-2.1.9-1 
    

- name: Run make install 
  community.general.make:
    chdir: /usr/local/src/noip-2.1.9-1
    target: install
    
- name: Ensure that noip2 is launched at boot
  lineinfile:
    path: /etc/rc.local
    line: sudo /usr/local/bin/noip2
    create: yes

