---
# tasks file for rpi-install-noip-dynamic-update-client

- name: Download the no-ip tar
  get_url:
    url: http://www.no-ip.com/client/linux/noip-duc-linux.tar.gz
    dest: /opt/noip

- name: Unpack the no-ip tar
  unarchive:
    src: /home/pi/noip/noip-duc-linux.tar.gz
    dest: /opt/noip
    remote_src: yes

- name: Install make
  apt:
    name: make
    state: present

- name: Install gcc
  apt:
    name: gcc
    state: present

- name: Run make
  community.general.make:
    chdir: /opt/noipnoip-2.1.9-1 
